# Generated by Django 5.0.6 on 2024-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeatures',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
